-- Generated by Yueyue
-- Main App
addappid(1576420)
-- Manifests
addappid(1576421, 1, "f76ad559310207144f63ba2498d5e424103d5beff81397496041435ac461684e")
setManifestid(1576421, "3373202489915929952")
