addappid(2306030)
addappid(2306031, 25804833984, "b717b1927d90220e4e426ec6f87854f67e2b94fa99b29aafbab8568e0eacb1db")
setManifestid(2306031, "6328330120919413290", 26366503976)


-- Generated By [Manifest Dumper v3.2.2.9] ~ Game: EBOLA VILLAGE
-- Discord: SteamDen ~ https://discord.gg/steamden