-- Generated by Yueyue
-- Main App
addappid(2443300)
-- Manifests
addappid(2443301, 1, "d7e7fef3d319e6e657c9727ad8b8917c0383d005814219d9f9d1824c19fcd246")
setManifestid(2443301, "4658189253346933996")
