-- Generated by Yueyue
-- Main App
addappid(2493670)
-- Manifests
addappid(2493671, 1, "f845612626f133add8f603edd2b2af798bc2360314b8177d363441eb94afb630")
setManifestid(2493671, "7770162796998214616")
