-- Generated by Yueyue
-- Main App
addappid(2964920)
-- Manifests
addappid(2964921, 1, "fe35caa5ff31ef8baad269c5daab90f34131cdaae5adbd56d9148c245be5ec78")
setManifestid(2964921, "6706196313811711463")
