-- Generated by Yueyue
-- Main App
addappid(3020970)
-- Manifests
addappid(3020972, 1, "468b7dadc685b90f4c7639120615cf8333f1b48c979fea969ddd235ef6b5979a")
setManifestid(3020972, "5549016982252194920")
