-- Generated by Yueyue
-- Main App
addappid(3080290)
-- Manifests
addappid(3080291, 1, "b9aceeafb3c05b97cab8216b02b817091db20832c0cfacaba3d588dabc56342b")
setManifestid(3080291, "6458375592874590692")
