-- Generated by Yueyue
-- Main App
addappid(3273990)
-- Manifests
addappid(3273991, 1, "ff6b866e740ad95d8e49b6a1eae3b39f236c7a840044e75df39b7f0308a6a410")
setManifestid(3273991, "7393042817434942305")
