-- Generated by Yueyue
-- Main App
addappid(381050)
-- Manifests
addappid(381052, 1, "0d5af39a69dd9f48c29914ec82b725fc0170519c95140578f4fdb203b89a0d9e")
setManifestid(381052, "2743790373193369388")
