-- Generated by Yueyue
-- Main App
addappid(384280)
-- Manifests
addappid(384281, 1, "de348af065a7135e0ea7889f6f9b721f2cdddd7623fb2a3cfa682e2c1f7845e8")
addappid(384285, 1, "3bc148198928eca916eaa5ef0aff58a6ddb5a99fbdf82d60539627b0a67df745")
setManifestid(384281, "4745898357596890237")
setManifestid(384285, "2403492322552170023")
