addappid(490110)
addappid(490111, 3690167792, "44bcc3870bf156385e37ff47e71ae28824fa905a542cdc8eaf05715799f78fc2")
setManifestid(490111, "8902698034020567750", 7949476862)


-- Generated By [Manifest Dumper v3.2.2.9] ~ Game: The Precinct
-- Discord: SteamDen ~ https://discord.gg/steamden